// <auto-generated />
using Library.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250719202721_AddBookIndexes")]
    partial class AddBookIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesInUse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Books_Category");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_Books_FirstName");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("IX_Books_ISBN_Unique");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Books_LastName");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Books_Status");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Books_Title");

                    b.HasIndex("Category", "Status")
                        .HasDatabaseName("IX_Books_Category_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Books_Author");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fiction",
                            CopiesInUse = 80,
                            FirstName = "Jane",
                            ISBN = "123456789",
                            LastName = "Austen",
                            Status = 0,
                            Title = "Pride and Prejudice",
                            TotalCopies = 100,
                            Type = "Hardcover"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fiction",
                            CopiesInUse = 65,
                            FirstName = "Harper",
                            ISBN = "123456782",
                            LastName = "Lee",
                            Status = 1,
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 75,
                            Type = "Paperback"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fiction",
                            CopiesInUse = 45,
                            FirstName = "J.D.",
                            ISBN = "123456783",
                            LastName = "Salinger",
                            Status = 2,
                            Title = "The Catcher in the Rye",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Non-Fiction",
                            CopiesInUse = 22,
                            FirstName = "F. Scott",
                            ISBN = "123456784",
                            LastName = "Fitzgerald",
                            Status = 0,
                            Title = "The Great Gatsby",
                            TotalCopies = 30,
                            Type = "Hardcover"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Biography",
                            CopiesInUse = 35,
                            FirstName = "Paulo",
                            ISBN = "123456785",
                            LastName = "Coelho",
                            Status = 1,
                            Title = "The Alchemist",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mystery",
                            CopiesInUse = 11,
                            FirstName = "Markus",
                            ISBN = "123456786",
                            LastName = "Zusak",
                            Status = 2,
                            Title = "The Book Thief",
                            TotalCopies = 75,
                            Type = "Hardcover"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
